module.exports = {
  algorithms: [
    {
      type: 'autogenerated',
      dirName: 'algorithms',
    },
  ],
  computerScience: [
    {
      type: 'autogenerated',
      dirName: 'cs',
    },
  ],
  frontend: [
    {
      type: 'autogenerated',
      dirName: 'frontend',
    },
  ],
  etc: [
    {
      type: 'autogenerated',
      dirName: 'etc',
    },
  ],
};
