name: Notion2Github
on:
  push:
    branches:
      - 'test/notion2github**'
  schedule:
    - cron: '0 14 * * *'

jobs:
  auto-sync-from-notion-to-github:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Notion2Github Algorithms
        uses: younho9/notion2github
        with:
          database-url: ${{ secrets.DATABASE_URL }}
          docs-directory: ./docs/algorithms
          filter-prop: Main Category
          filter-value: Algorithms
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}

      - name: Notion2Github CS
        uses: younho9/notion2github
        with:
          database-url: ${{ secrets.DATABASE_URL }}
          docs-directory: ./docs/cs
          filter-prop: Main Category
          filter-value: CS
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}

      - name: Notion2Github ETC
        uses: younho9/notion2github
        with:
          database-url: ${{ secrets.DATABASE_URL }}
          docs-directory: ./docs/etc
          filter-prop: Main Category
          filter-value: ETC
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}

      - name: Notion2Github Frontend
        uses: younho9/notion2github
        with:
          database-url: ${{ secrets.DATABASE_URL }}
          docs-directory: ./docs/frontend
          filter-prop: Main Category
          filter-value: Frontend
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}

      - name: Notion2Github Log
        uses: younho9/notion2github
        with:
          database-url: ${{ secrets.DATABASE_URL }}
          docs-directory: ./log
          filter-prop: Main Category
          filter-value: Log
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}

      - name: Format documents
        uses: creyD/prettier_action@v3.1
        with:
          prettier_options: --write ./docs/**/*.md ./log/**/*.md
          commit_message: 'docs: Update docs (auto)'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
